### ISSUE TITLE
how check if it's working?

### ISSUE THREAD

**Issue by cocodrino** [userexec/Sendy-BEE-free-Uploader#2]
Hi..I followed the installation guide but I can't find the new button for upload files, I'm not receiving any warning or error, everything looks identical as before, how can I check if this extension is working?, any log or debug info?

thank you!

**Comment by userexec** [comment]
Ack, that's the trickiest part for sure. If it's not there after a few refreshes, then it's an issue with CKEditor not registering it. One of these days I'm going to start having nightmares about CKEditor ignoring configurations.

I won't be able to look at this today, but next time I get a bit I'll do a clean local install of Sendy and run through the configuration steps again to make sure I'm not missing any details in there that could cause CKEditor to miss the plugin.

**Comment by userexec** [comment]
It occurred to me though that the permissions on the plugin folder may be preventing CKEditor from seeing the files. I did forget to make a note in the instructions about updating the file permissions once they're in place. If you haven't already, do a `sudo chmod -R 755 [the plugin folder]`.

**Comment by cocodrino** [comment]
thanks man, after change the permission I'm able to see the icon in the editor, now when I select the bee file to upload and press ok, the modal close but seems than it's not doing nothing more, I can't see some details or info about what is it doing...do you know how can I debug or get logs about it?

thanks!

**Comment by cocodrino** [comment]
[seems](http://help.beefree.io/hc/en-us/articles/203135882-Sample-code-and-templates) than you can integrate the bee editor in any project, would be cool integrate with sendy, has you tried it?..

**Comment by userexec** [comment]
You should be able to get some debugging info on what it's running into by tailing your PHP logs, so for an Ubuntu system probably `tail -f /var/log/apache2/error.log`, then try uploading again and watch what errors come in on the console.

I've seen the editor but haven't tried putting it in Sendy yet. Trouble is that would require modifying Sendy core files and would complicate updates and endanger uptime. If I were running my instance as a personal one I might go for it, but at work our core modifications have become a real thorn in my side.
