### ISSUE TITLE
Error: Not a valid BEE free email archive.

### ISSUE THREAD

**Issue by ivankozlik** [userexec/Sendy-BEE-free-Uploader#4]
When I try to upload the beefree.io zip archive I'm getting this error: Error: Not a valid BEE free email archive. Previously everything worked fine. I didn't change anything and now it won't upload.

**Comment by mnogolik** [comment]
if (!preg_match('/(\.jpg$|\.jpeg$|\.png$|\.html$|\.doc$|\.docx$|\.pdf$|\.xls$|\.xlsx$|\.csv$|\.DS_Store$|\._fileName$|\._images$)/', $name)) {
					throw new RuntimeException('Error: Not a valid BEE free email archive.');

It doesn't accept files where extension is in capital letters  for instance: image.JPG

**Comment by mcdent** [comment]
I too am receiving the same error?
Is there anything I can do. 
Thanks

**Comment by mnogolik** [comment]
add extension with in capital letters to the filter.

**Comment by mcdent** [comment]
Thanks, but I checked in the image folder of the BEE zip file and all the files have lower case extensions?

**Comment by mnogolik** [comment]
well there might be some other files that couldn't go through this filter

**Comment by mcdent** [comment]
I created a basic BEE email with just a text block, this imported fine.
I then added a single gif image. This failed with the above error.
I checked inside he zip and it is just a file.gif file located within the images folder.
Not sure why this is breaking it?

**Comment by mnogolik** [comment]
@mcdent do you see gif extension in the filter list? Neither I, so it's quite expect able that it fails.

**Comment by mcdent** [comment]
my bad, it was missing the .gif . Thanks.

**Comment by userexec** [comment]
Filter has been updated to accept .gif extensions and be case insensitive. Thanks!
