### ISSUE TITLE
Set up upload file size

### ISSUE THREAD

**Issue by q23** [userexec/Sendy-BEE-free-Uploader#6]
Please set up a little bit:
https://github.com/userexec/Sendy-BEE-free-Uploader/blob/master/plugin_endpoint.php#L57

**Comment by userexec** [comment]
Addressed in [29e70b6](https://github.com/userexec/Sendy-BEE-free-Uploader/commit/29e70b6ed4cb4e5f7d01cf3a98b09a15645bb647)
